    modLoader="javafml"
    loaderVersion="${loader_version_range}"
    license="${mod_license}"
[[mods]]
    modId="${mod_id}"
    version="${mod_version}"
    displayName="${mod_name}"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/knight-quest-reforged"
    logoFile="knightquest.png"
    authors="${mod_authors}"
    description='''${mod_description}'''
[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="knightlib"
    mandatory=true
    versionRange="[1.0.0,)"
    ordering="NONE"
    side="BOTH"